import serial

# accumulator configuration
NUM_BANKS = 8
NUM_ACTIVE_BANKS = 2
NUM_CELLS_PER_BANK = 17

MIN_VOLTAGE = 3.0
MAX_VOLTAGE = 4.2
MIN_TEMPERATURE = 0
MAX_TEMPERATURE = 60

# serial configuration
PORT = '/dev/cu.usbmodem142303'
BAUDRATE = 115200
# BYTESIZE = serial.SEVENBITS
BYTESIZE = 7

#PARITY = serial.PARITY_EVEN
PARITY = 'E'

#STOPBITS = serial.STOPBITS_ONE
STOPBITS = 1


# messages
BITS_PER_MESSAGE_ID = 3
BITS_PER_BANK_ID    = 3
BANK_ID_MASK 		= 0b00111000
MESSAGE_ID_MASK		= 0b00000111

VOLTAGE_ID 			= 0b000
TEMPERATURE_ID 		= 0b001
DISCHARGE_ID        = 0b010

